spring:
  application:
    name: tracking-number
  datasource:
    # for local development
#    url: jdbc:mysql://localhost:3306/shipping
#    username: admin
#    password: admin

    # for cloud
    url: jdbc:mysql://sql12.freesqldatabase.com:3306/sql12773474?useSSL=false&allowPublicKeyRetrieval=true&disableDnsCaching=true&autoReconnect=true
    username: sql12773474
    password: gEXXFMnNAH
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  redis:
#    host: localhost
#    port: 6379